name: Continuos Integration with GitHub
on:
  push:
    branches:
      - main
    pull-request:
      branches:
        - main
  jobs:
    test_build:
      runs_on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: clean project
          run: ./gradlew clean
        - name: run all test
          run: ./gradlew testClasses
        - name: create .jar and install
          run: ./gradlew bootJar