name: Continuous Integration with GitHub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Limpiar proyecto
        run: ./gradlew clean

      - name: Ejecutar pruebas
        run: ./gradlew test