name: Continuous Integration with GitHub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Esto deberia ser exitoso
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs